name: Lint

on:
  push:
    branches: ["*"]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check form
        run: find src -name '*.hpp' -o -name '*.cpp' | xargs clang-format -i

      - name: Check for formatting changes
        run: git diff --exit-code
